services:

  annotrieve-nginx:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /home/emilior/annotrieve-project/annotrieve/files:/data/annotrieve/files:ro
      - /home/emilior/annotrieve-project/annotrieve/logs:/var/log/nginx
    ports:
        - "94:80" 

  annotrieve-mongo:
    image: mongo:8.0
    env_file:
      - .env
    restart: always
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
     - /home/emilior/annotrieve-project/annotrieve-db:/data/db
    ports:
      - "27021:27017"
    logging:
      driver: "none"

  annotrieve-redis:
    image: "redis:alpine"
    expose:
      - "6379"

  annotrieve-fastapi:
    build: ./server
    container_name: annotrieve-fastapi
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

    volumes:
      - ./server:/home/appuser/app
      - /home/emilior/annotrieve-project/annotrieve/files:${LOCAL_ANNOTATIONS_DIR}
      - /home/emilior/annotrieve-project/annotrieve/logs:${LOCAL_LOGS_PATH}:ro
    env_file:
      - .env
    depends_on:
      - annotrieve-redis
      - annotrieve-mongo
    ports:
      - "5002:5000"  # Exposing on a different port to avoid conflicts

  annotrieve-fastapi-celery:
    build: ./server
    command: celery --app celery_app.celery_worker.app worker --loglevel=info --autoscale=1,1 --max-tasks-per-child=1
    volumes:
      - ./server:/home/appuser/app
      - /home/emilior/annotrieve-project/annotrieve/files:${LOCAL_ANNOTATIONS_DIR}
      - /home/emilior/annotrieve-project/annotrieve/logs:${LOCAL_LOGS_PATH}:ro
    env_file:
      - .env
    depends_on:
      - annotrieve-fastapi
      - annotrieve-mongo
      - annotrieve-redis

  annotrieve-fastapi-celery-beat:
    build: ./server
    command: celery --app celery_app.celery_worker.app beat --loglevel=info
    volumes:
      - ./server:/home/appuser/app
      - /home/emilior/annotrieve-project/annotrieve/files:${LOCAL_ANNOTATIONS_DIR}
      - /home/emilior/annotrieve-project/annotrieve/logs:${LOCAL_LOGS_PATH}:ro
    env_file:
      - .env
    depends_on:
      - annotrieve-fastapi
      - annotrieve-mongo
      - annotrieve-redis

volumes:
  app:
  mongodb-data:
  celerybeat-schedule:
